### PR TITLE
Basic AST parsing and some starter diagnostics

### PR DESCRIPTION
**Pull request by jargonzombies**
This is kind of a big PR, but I hope you'll find it worth your while.

This introduces basic AST parsing on the basis of the grammar you wrote. I made a duplicate grammar that
- suppresses all the whitespace and comments
- distinguish control flow (conditionals, loops, function/macro declarations) from regular command invocations
- adds block-level expectation parsing (opening a `function` implies there must be an `endfunction` somewhere)
- adds semantic actions to generate AST nodes

The cool thing about the expectation parsing (using the `-` instead of `+`) is that it can get you get an exception if you forget to close a block, which can be easily converted into a diagnostic!

Adds `TEXT_DOCUMENT_DID_OPEN`/`_SAVE` features to the language server, which parses the file into an AST and generates diagnostics for single list file only. If the AST parsing was successful, it gets traversed by a bunch of diagnostic-generating visitors much in the style of python's AST module (i.e. if the visitor has a `visit_<ASTNode-type-name>` method matching the type of the node being visited, that function gets called).

I've only added the following diagnostics, whose logic may or may not be flawed at this point:
- `break()` or `continue()` not enclosed in a loop
- `return()` in a macro (suggest replacement with `message(FATAL_ERROR ...)`)
- redundant assignment: `set(asdf ${asdf})` (Yeah, I got bit by this recently :grimacing:)
- duplicate branch in `if/elseif`
- all-uppercase commands (suggest lowercase)
- directory-based api (suggest replacement with target-based api)

Naturally, these are all up for discussion or omission. They're kind of a starter list, since I bet there's a bunch more helpful diagnostics that could be implemented. But maybe we should decide on the general structure for them first, hence this PR.

I also messed around a little in the rest of the files. Fixed a few misspellings and added documentation in some places when I was first trying to find my way around the code.

### CODE REVIEW

**Comment by regen100** [comment]
Thanks for the PR. Diagnostics is a fascinating feature for this LSP. I'd love to merge this great PR, but I'm considering refactoring, so I won't merge this at this time.

I'm considering replacing the parser and formatter with [cheshirekow/cmake_format](https://github.com/cheshirekow/cmake_format). Initially, I was only thinking of replacing the parser and the formatter, but this PR made me think that it would be a good idea to integrate `cmake-lint` as a diagnostic.

In addition, thank you for correcting the misspelling and adding the documentation. It's ready to be merged in, so if you send me a PR with this part cut out, I'll merge it in.

**Comment by jargonzombies** [comment]
I agree that `cmakelint` is a great tool. I use it myself currently. But I think you should reconsider the value of the diagnostic part of this PR. `cmakelint` lints style and convention issues by doing single-line parsing with simple regexes. This AST parsing opens the path to semantic linting, actually understanding what is being done in a whole tree of CMake files. That's an entirely different category of diagnostics we could offer here. There's context for each invocation. You already put in the work to make a parser for the CMake grammar, I think it would be a shame to throw that away.

I'll split off the documentation and misspelling part.

**Comment by regen100** [comment]
The `cmake-lint` also supports more complex linting. For example, [`E0103`](https://github.com/cheshirekow/cmake_format/blob/904c42da298f7fda932d9ac774517c20e2667fb8/cmakelang/lint/basic_checker.py#L601) traverses the tree when it finds a `break()` or `continue()` to determine whether it's in a loop. This provides the same functionality as your `OrphanedLoopCommand` (but I like your code because it's more structured and easier to read).

I am concerned that there are two implementations for the same purpose. This increases maintenance costs. If you want to deal with semantics that the current `cmake-lint` can't handle, it is better to extend `cmake-lint`.
From the point of view of the separation of concerns principle, it would be better design for LSP to concentrate on communicating with the editor and delegate the diagnostic functions to `cmake-lint`.

**Comment by jargonzombies** [comment]
Ah, now I see. I was confused because I thought you meant [this project](https://github.com/richq/cmake-lint). I wasn't aware `cmake-format` had these kinds of lints. I'll have a look and see if this PR has some value there. Thanks for the advice!

**Comment by regen100** [comment]
Sorry, I should have made that explicit. [`cheshirekow/cmake_format`](https://github.com/cheshirekow/cmake_format) on GitHub is also distributed as [`cmakelang`](https://pypi.org/project/cmakelang/) renamed from [`cmake-format`](https://pypi.org/project/cmake-format/) on PyPI and offers `cmake-format` commands as well as `cmake-lint` commands (I'm confused too).

**Pull request closed without merging**
